export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const GET_POKEMON_SPECIES = 'GET_POKEMON_SPECIES';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const SET_LOADING = 'SET_LOADING';
export const POKEMON_ERROR = 'POKEMON_ERROR';
export const FILTER_POKEMONS = 'FILTER_POKEMONS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
